version: '3.9'
services:
  cart_service:
    container_name: cart_service
    build:
      context: /Users/younesabdelwadoud/Downloads/cart-service-master
      dockerfile: /Users/younesabdelwadoud/Downloads/cart-service-master/src/main/resources/Dockerfile
    depends_on:
      carts_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products_db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  carts_db:
    image: 'postgres:latest'
    container_name: carts_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - 5455:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5